// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';
// ignore: depend_on_referenced_packages
import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/task_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 1394578162495894502),
      name: 'TaskModel',
      lastPropertyId: const IdUid(5, 8463162557404214097),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7021755951525279745),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8644226983360325666),
            name: 'taskTitle',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7341508275305672346),
            name: 'taskDescription',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5077186663323593963),
            name: 'taskDone',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8463162557404214097),
            name: 'creationDate',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 1394578162495894502),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [1993991042403371585],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        8550848249623695348,
        8696683925991445787,
        3867518219191406806,
        4641575035938944439,
        6020424376089655714
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TaskModel: EntityDefinition<TaskModel>(
        model: _entities[0],
        toOneRelations: (TaskModel object) => [],
        toManyRelations: (TaskModel object) => {},
        getId: (TaskModel object) => object.id,
        setId: (TaskModel object, int id) {
          object.id = id;
        },
        objectToFB: (TaskModel object, fb.Builder fbb) {
          final taskTitleOffset = object.taskTitle == null
              ? null
              : fbb.writeString(object.taskTitle!);
          final taskDescriptionOffset = object.taskDescription == null
              ? null
              : fbb.writeString(object.taskDescription!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, taskTitleOffset);
          fbb.addOffset(2, taskDescriptionOffset);
          fbb.addBool(3, object.taskDone);
          fbb.addInt64(4, object.creationDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final creationDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = TaskModel(
              creationDate: creationDateValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(creationDateValue),
              taskDescription: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              taskTitle: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              taskDone: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 10))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TaskModel] entity fields to define ObjectBox queries.
class TaskModel_ {
  /// see [TaskModel.id]
  static final id = QueryIntegerProperty<TaskModel>(_entities[0].properties[0]);

  /// see [TaskModel.taskTitle]
  static final taskTitle =
      QueryStringProperty<TaskModel>(_entities[0].properties[1]);

  /// see [TaskModel.taskDescription]
  static final taskDescription =
      QueryStringProperty<TaskModel>(_entities[0].properties[2]);

  /// see [TaskModel.taskDone]
  static final taskDone =
      QueryBooleanProperty<TaskModel>(_entities[0].properties[3]);

  /// see [TaskModel.creationDate]
  static final creationDate =
      QueryIntegerProperty<TaskModel>(_entities[0].properties[4]);
}
